### ISSUE TITLE
Dettagli non visibili in wp-admin

### ISSUE THREAD

**Issue by specialworld83** [italia/design-wordpress-theme-wt#10]
Buongiorno, 

sto a lavorare per un sito scolastico ma dal pannello di controllo non visualizza i dettagli del tema.

Versione PHP 7.4

Come mai?

**Comment by francescozaia** [comment]
Ciao. @specialworld83 non ti so aiutare nel dettaglio, ma ti volevo segnalare la presenza di un [kit per i siti delle scuole](https://designers.italia.it/kit/scuole/) con un [tema wordpress dedicato](https://github.com/italia/design-scuole-wordpress-theme).
