### ISSUE TITLE
Uncaught Error: [] operator not supported for strings in functions.php

### ISSUE THREAD

**Issue by F4bri92** [italia/design-wordpress-theme-wt#4]
Dentro functions.php nella funzione **italiawp_custom_classes_menu_utilita** $classes viene prima definito come stringa e poi trattato come array.

```
$classes = "";
$classes[] = 'Grid-cell u-sizeFull u-sm-size1of2 u-md-size1of4 u-lg-size1of4';
```

**Comment by francescozaia** [comment]
Ciao @F4bri92,
Grazie per il contributo, nello specifico credo si tratti di una svista.
Ho visto che hai aperto anche altre issue e mi sembra tu abbia esperienza a riguardo, se te la senti puoi anche considerare di proporre delle pull request così che riusciamo a condividere i fix con tutti.
Grazie!

PS: ovviamente se ti serve una mano, scrivici pure!

**Comment by borisamico** [comment]
Risolto nella versione 1.1.2
