### ISSUE TITLE
Icone su box servizi

### ISSUE THREAD

**Issue by oraziov** [italia/design-wordpress-theme-wt#5]
Ciao, volevo sapere se fosse possibile inserire icone .svg accanto al testo dei box servizi, perchè usando il tag html <img src> non riesco ad adattarle alle dimensione che desidero.

Grazie

**Comment by borisamico** [comment]
Salve, dalla versione 1.5.3 è possibile inserire delle immagini sotto forma di icona nel menu box servizi inserendo direttamente il tag html < img class="icona" src="URL" > nel Testo del link
