### ISSUE TITLE
Content in pagina home

### ISSUE THREAD

**Issue by micfio** [italia/design-wordpress-theme-wt#7]
Impostando una pagina statica Home e una pagina statica per gli articoli aggiungendo dei contenuti e dei widget di site origin con editor classic questi non vengono visualizzati in Home. Dipende dal tema o sono io che sbaglio qualcosa? Grazie

**Comment by micfio** [comment]
Ho risolto in parte richiamando la funzione the_content() all'interno del file home-section.php del template. adesso posso inserire del contenuto personalizzato come sezione all'interno del sito.
Mi chiedevo si potrebbe implementare una funzione di ricerca per data range nel template allo scopo di filtrare le informazioni piu velocemente? Se i contenuti sono in numero considerevole risulta tedioso sfogliare le pagine. Grazie

**Comment by borisamico** [comment]
Grazie per la segnalazione, seguirò il suggerimento nella prossima versione.
