### ISSUE TITLE
Ricerca per data Nel template

### ISSUE THREAD

**Issue by micfio** [italia/design-wordpress-theme-wt#8]
Salve Ho aggiunto questo codice nel file function.php del tema per effettuare una ricerca per data .Il codice e stato adattato da un post di stackoverflow.
``function my_date_search() {

    if(is_search()) {

        $search_query = get_search_query();
        $months = array( 1 => "Gennaio", 2 => "Febbraio", 3 => "Marzo", 4 => "Aprile", 5 => "Maggio", 6 => "Giugno", 7 => "Luglio", 8 => "Agosto", 9 => "Settembre", 10 => "Ottobre", 11 => "Novembre", 12 => "Dicembre" );

        foreach($months as $month => $month_name) {
            if(stristr($search_query, $month_name)) {
                $m = $month;
                preg_match('/(19[0-9][0-9]|20[0-9][0-9])/', $search_query, $year);
                if($year)
                    $y = $year[0];
                preg_match('/^[0-3]{0,1}[0-9]{1} /', $search_query, $day);
                if($day)
                    $d = $day[0];
            }
        }

        if(isset($d) || isset($m) || isset($y)) {
            $wd = explode($y, $search_query);

            if($wd[1])
               $query_string = 's=' . trim($wd[1]) . '&year=' . $y . '&monthnum=' . $m . '&day=' . $d;
            else
            $query_string = 'year=' . $y . '&monthnum=' . $m . '&day=' . $d;
            echo $query_string;
            query_posts($query_string);
            $search_query = get_search_query();

        }
    }
}
add_action('get_header', 'my_date_search');``

La ricerca funziona alquanto bene inserendo delle query come Agosto, Agosto 2019, 19 Agosto 2019 riesco a filtrare i post , pero ho un problema sulla paginazione, sfogliando le pagine a partire dalla 2 ottengo un errore 404. Potreste darmi una mano ? non so come procedere, sembra corretto.
Grazie Anticipatamente

**Comment by micfio** [comment]
Risolto con questo codice :`add_action('pre_get_posts','my_date_search');
    function my_date_search() {

    if(is_search()) {

        $search_query = get_search_query();
        $months = array( 1 => "Gennaio", 2 => "Febbraio", 3 => "Marzo", 4 => "Aprile", 5 => "Maggio", 6 => "Giugno", 7 => "Luglio", 8 => "Agosto", 9 => "Settembre", 10 => "Ottobre", 11 => "Novembre", 12 => "Dicembre" );

        foreach($months as $month => $month_name) {
            if(stristr($search_query, $month_name)) {
                $m = $month;
                preg_match('/(19[0-9][0-9]|20[0-9][0-9])/', $search_query, $year);
                if($year)
                    $y = $year[0];
                preg_match('/^[0-3]{0,1}[0-9]{1} /', $search_query, $day);
                if($day)
                    $d = $day[0];
            }
        }
        $paged = ( get_query_var( 'paged' ) ) ? get_query_var( 'paged' ) : 1;
        if(isset($d) or isset($m) or isset($y)) {
            $wd = explode($y, $search_query);


            if($wd[1])
               $query_string = 's=' . trim($wd[1]) . '&year=' . $y . '&monthnum=' . $m . '&day=' . $d . '&post_per_page=6' . '&paged='.$paged;
            else
            $query_string = 'year=' . $y . '&monthnum=' . $m . '&day=' . $d . '&post_per_page=6' . '&paged='.$paged;

            query_posts($query_string);

    }
    }
}
add_action('get_header', 'my_date_search');`

**Comment by borisamico** [comment]
Grazie mille, integrerò il suo codice nella prossima versione!
